name: Run Apartments Finder

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Google Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip google-chrome-stable
        wget "https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        echo "Google Chrome version: $(google-chrome --version)"
        echo "ChromeDriver version: $(chromedriver --version)"

    - name: Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Debug Environment
      run: |
        source venv/bin/activate
        pip freeze
        which python
        python --version
        which chromedriver
        chromedriver --version
        which google-chrome
        google-chrome --version

    - name: Run Apartments Finder Script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TELEGRAM_BOT_API_KEY: ${{ secrets.TELEGRAM_BOT_API_KEY }}
        TELEGRAM_BOT_APARTMENTS_GROUP_CHAT_ID: ${{ secrets.TELEGRAM_BOT_APARTMENTS_GROUP_CHAT_ID }}
        FACEBOOK_USERNAME: ${{ secrets.FACEBOOK_USERNAME }}
        FACEBOOK_PASSWORD: ${{ secrets.FACEBOOK_PASSWORD }}
        FACEBOOK_GROUPS: ${{ secrets.FACEBOOK_GROUPS }}
        FACEBOOK_BACKUP_CODES: ${{ secrets.FACEBOOK_BACKUP_CODES }}
        PYTHONPATH: ${{ github.workspace }}/apartments-finder
        SELENIUM_CHROMEDRIVER: /usr/local/bin/chromedriver
      run: |
        source venv/bin/activate
        python -m apartments_finder.main
