name: Run Apartments Finder

on:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Apartments Finder Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_BOT_API_KEY: ${{ secrets.TELEGRAM_BOT_API_KEY }}
          TELEGRAM_BOT_APARTMENTS_GROUP_CHAT_ID: ${{ secrets.TELEGRAM_BOT_APARTMENTS_GROUP_CHAT_ID }}
          TELEGRAM_BOT_APARTMENTS_LOGS_GROUP_CHAT_ID: ${{ secrets.TELEGRAM_BOT_APARTMENTS_LOGS_GROUP_CHAT_ID }}
          FACEBOOK_USERNAME: ${{ secrets.FACEBOOK_USERNAME }}
          FACEBOOK_PASSWORD: ${{ secrets.FACEBOOK_PASSWORD }}
          FACEBOOK_GROUPS: ${{ secrets.FACEBOOK_GROUPS }}
          FACEBOOK_BACKUP_CODES: ${{ secrets.FACEBOOK_BACKUP_CODES }}
          PYTHONPATH: ${{ github.workspace }}  # Include the root directory in PYTHONPATH
        run: |
          source venv/bin/activate
          python apartments_finder/main.py  # Run the script directly
