name: Run Apartments Finder

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  # Check out the repository

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Google Chrome and ChromeDriver
      run: |
        sudo apt-get update
        wget -qO- https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        CHROME_VERSION=$(google-chrome --version | grep -oP '[0-9.]+')
        echo "Installed Google Chrome version: $CHROME_VERSION"
        CHROMEDRIVER_VERSION=$(wget -qO- "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        wget "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        echo "Installed ChromeDriver version: $(chromedriver --version)"

    - name: Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install selenium  # Explicitly install selenium

    - name: Debug Environment
      run: |
        source venv/bin/activate
        pip freeze  # List installed packages
        which python  # Verify Python binary location
        python --version  # Ensure correct Python version is used
        which google-chrome
        google-chrome --version
        which chromedriver
        chromedriver --version
        ls -l  # List project files
        ls -l apartments_finder/  # Verify module structure

    - name: Run Apartments Finder Script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TELEGRAM_BOT_API_KEY: ${{ secrets.TELEGRAM_BOT_API_KEY }}
        TELEGRAM_BOT_APARTMENTS_GROUP_CHAT_ID: ${{ secrets.TELEGRAM_BOT_APARTMENTS_GROUP_CHAT_ID }}
        FACEBOOK_USERNAME: ${{ secrets.FACEBOOK_USERNAME }}
        FACEBOOK_PASSWORD: ${{ secrets.FACEBOOK_PASSWORD }}
        FACEBOOK_GROUPS: ${{ secrets.FACEBOOK_GROUPS }}
        FACEBOOK_BACKUP_CODES: ${{ secrets.FACEBOOK_BACKUP_CODES }}
        PYTHONPATH: ${{ github.workspace }}/apartments-finder  # Explicitly set PYTHONPATH
      run: |
        source venv/bin/activate
        python -m apartments_finder.main  # Run the script as a module
